### ISSUE TITLE
Issue with "Problems" section

### ISSUE THREAD

**Issue by joseaguardia** [NagiosEnterprises/nagioscore#109]
Hi!

In left menu oh Nagios Core 4.1.1, both "Problems" and "Services" links to the same URL (http://domain/nagios/cgi-bin/status.cgi?host=all&servicestatustypes=28

I think that "Problems" may display ALL problems (including services and hosts), and it doesn't work so.

Regards and thank in advance.

**Comment by jfrickson** [comment]
There isn't a good way to have it display all problems, so I removed the link from the "Problems" list item.

Fixed in commit https://github.com/NagiosEnterprises/nagioscore/commit/ea6db3d92a88cbff3f753b5011b9b37c9ded2166
on branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1
