### ISSUE TITLE
Nagios Core Build for POWER Linux Platform

### ISSUE THREAD

**Issue by gynayak2** [NagiosEnterprises/nagioscore#117]
To be able to build & run the Nagios application on IBM's POWER Platform, there were some changes made in the Fedora Quickstart guide. The changes done for POWER (POWER 8) platform are highlighted in blue color in the attached POWER Linux QuickStart guide. Suggesting that this guide be published here under the Installation Guides section: https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/quickstart.html

This will enable the Nagios application to run and monitor from POWER system. Testing has been performed to verify that the Nagios monitoring features work as expected when running the application on  POWER platform.

[POWER Linux Quickstart.pdf](https://github.com/NagiosEnterprises/nagioscore/files/167804/POWER.Linux.Quickstart.pdf)

**Comment by tmcnag** [comment]
Can you please be more specific?  This page is for reporting issues with the software, not for requesting builds for a particular architecture.  If you are running into a problem compiling or running the software, please provide a description of the problem along with any relevant errors.

**Comment by gynayak2** [comment]
This new issue created to address installation problem in IBM POWER platform.

 As refer to the response from Scott Wilkerson <swilkerson@nagios.com> "This sounds great!  The easiest way to give back to the Nagios project would be to create a pull request or issue on the official Nagios Project Git Repository found here
https://github.com/NagiosEnterprises/nagioscore".

**Comment by scottwilkerson** [comment]
Sorry @gynayak2 I was under the impression that you had to make changes to the code, which is why I had directed you here.

Being this is more of a installation guide, it would actually be more appropriate in the Nagios Exchange.  Would you be willing to post the PDF here?
https://exchange.nagios.org/directory/Documentation/Nagios-Core-Documentation

Then I would be more than willing to link the quickstart page to the PDF in the Nagios Core Documentation.

Thanks!

**Comment by scottwilkerson** [comment]
Link added to guide.

Thanks!
