### ISSUE TITLE
Adding setting in nagios.cfg to not sorting host groups when  displaying  on Web

### ISSUE THREAD

**Issue by tjyang** [NagiosEnterprises/nagioscore#147]
Hi 
This is an request for enhancement to add a variable in nagios.cfg  to allow user to decide whether to sort host groups by default.

**Comment by jfrickson** [comment]
Is there a particular reason you don't want the groups sorted?

**Comment by ericloyd** [comment]
Hey, as long as we're sorting things, then let's also be able to sort by other things:

- Alphabetically
- How many items are in the group
- How many things in an OK state
- How many things in a non-OK state

Of course, all of the above should be able to go asc/desc sorted as well.

**Comment by tjyang** [comment]
@jfrickson , to you question below

```
>Is there a particular reason you don't want the groups sorted?
```
Sorting groups by default is ok for other Nagios users. This is a request to have one variable like hostgroup_sorting=0 to disable the default sorting. I  need a host's first group in hosts.cfg always showing as first hostgroup on web page.  This will allow us to have our NOC team only look at 1st group from webpage to have certain action.

**Comment by willemdh** [comment]
Sorry but this seems a very weird fr to me. Sorting should be standard everywhere. If you want to list some hostgroup first, why no prepend it with an underscore or some character in the beginning of the alphabet?

**Comment by ericloyd** [comment]
I can see this going many ways.  Mainly, because I can see that host groups may have to follow some sort of naming standard that precludes using AAA-group1 and BBB-group2 type forcing functions.

**Comment by hedenface** [comment]
@willemdh It does to me as well. The way it is is the way it is - we've all been dealing with it. I'm not usually a proponent of "lets do this thing because that's the way it's always been done" - but in this case, I think I'd rather not change anything that millions (tens? hundreds? thousands?) of people are used to.

I'll close this, and if there is greater community feedback regarding the implementation, we'll consider it.

Thanks guys.
