### ISSUE TITLE
Services aren't checked after excluded time periods

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#196]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000465](http://tracker.nagios.org/view.php?id=0000465)  - Please follow that link for details.
> Originally submitted on 2013-06-24 by andrewharford

As reported previously (http://tracker.nagios.org/view.php?id=57) checks which have time period exclusion are not rechecked until midnight following the end of the exclusion period.

This bug seems to still be present on 3.5.0, while he documentation indicates that this feature should work as expected
 * http://nagios.sourceforge.net/docs/nagioscore/3/en/objectdefinitions.html#timeperiod
 * http://nagios.sourceforge.net/docs/nagioscore/3/en/oncallrotation.html

If this is the same known issue can the documentation please be updated? Otherwise, if this is a new issue, please let me know what information would be helpful in understanding the problem.

**Comment by jfrickson** [comment]
See also http://tracker.nagios.org/view.php?id=0000527

**Comment by minusdavid** [comment]
Yikes... sad to see this one still open. I'm finding this to be the case in 3.5.1.

I've also found the same behaviour for the following:

monday 3 00:00-12:47,13:30-24:00

If you run a check at 12:47, the next check should be at 13:30, but it's not. Instead, it's re-scheduled to the next day (provided you're otherwise having a 24x7 schedule).

**Comment by minusdavid** [comment]
I haven't checked on newer versions of Nagios... I'm on RHEL 6.8 at the moment using the EPEL 6 repo. 

However, since this bug is still open, I'm guessing it still exists.

Going to point out that this issue has existed since "3.2.0 – 08/12/2009":
https://www.nagios.org/projects/nagios-core/history/3x/

As a result, the documentation for 3.X should probaby be amended:
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html

There is mention of a fix for exclude in the notes for "4.1.1 – 08/19/2015" or rather that the fix doesn't work for dependencies.
https://www.nagios.org/projects/nagios-core/history/4x/

**Comment by minusdavid** [comment]
As an aside, I'm getting a connection refused for http://tracker.nagios.org/view.php?id=0000527

**Comment by jfrickson** [comment]
The change for 4.1.1 should not have effected this issue at all. However, I just tested it (used 13:30-13:40 exclusions) and at 13:41, I got a notification. So this was apparently fixed somewhere along the way. If I had to guess, I'd say 4.0.0.
