### ISSUE TITLE
Next scheduled active [host] check displays incorrect date and time following an on demand host check

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#199]
This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000482](http://tracker.nagios.org/view.php?id=0000482)  - Please follow that link for details.

**Comment by jfrickson** [comment]
_**Additional Details from Original Issue in Tracker**_

Following an upgrade to 3.5.1, I enabled active host checks for the first time. Up until now, I have always used active service checks with on demand host checks so would never have noticed this issue before so the problem may have been introduced in an earlier version.

When an on demand check is performed on a host, the date and time in the “Next Scheduled Active Check:” field in the “Host State Information” box duplicates the date and time displayed in the “Last Check Time:” field instead of the date and time based on check_interval. Note that this is only a display error as the next active check runs at the correct time. Once the next active check has run, the date and time is displayed correctly.

The date and time is also displayed incorrectly in the “Next Check” column of the “Check Scheduling Queue” report. The report gives the impression that a load of checks at the top have been scheduled in the past.

**Comment by jfrickson** [comment]
Really old problem (v3.5.1). My testing shows proper behavior, so it was probably fixed sometime between then (Sep 2013) and now.
