### ISSUE TITLE
Make sticky status for acks and comments configurable

### ISSUE THREAD

**Issue by abrist** [NagiosEnterprises/nagioscore#20]
See the following tracker:
http://tracker.nagios.org/view.php?id=234

It should be configurable in cgi.cfg or nagios.cfg.

**Comment by vAndrewJ** [comment]
+1 This topic has reared it's head again. Our NOC often opens support tickets for our engineers on WARNING state alerts and ack them with the ticket number. If the check goes to CRITICAL, they want the NOC to see it on the OpsScreen again and escalate the ticket. We're trying to train them to uncheck "sticky" but the whole "old dogs, new tricks" scenario plays out all too well.

**Comment by tmcnag** [comment]
Would make more sense to put this in cgi.cfg since the cmd.cgi file is what creates the web page and handles all this logic.  I'll take a look at a config option, otherwise a compiler flag might be an okay alternative since switching between default behaviors isn't as likely to happen.

**Comment by tmcnag** [comment]
Implemented here:  https://github.com/tmcnag/nagioscore/commit/e1d5a38967a6e3338f82a7f968dd36c394c2c339

You can add **ack_no_sticky=1** and/or **ack_no_send=1** to cgi.cfg to uncheck the "Sticky Acknowledgement" and "Send Notification" options respectively by default, no restart required.

Setting either option to **0** has the same effect as removing the line from the config.

Default behavior if an option is omitted/set to 0 is to leave the box checked, which is the behavior currently in Core.

Going to leave the behavior of "Persistent" as-is for now since there is already some logic to enable/disable it depending on the action taken.
