### ISSUE TITLE
bug in macros from the TOTALHOSTSERVICES* group

### ISSUE THREAD

**Issue by tmcnag** [NagiosEnterprises/nagioscore#208]
> This issue has been automatically migrated from [http://tracker.nagios.org/view.php?id=0000549](http://tracker.nagios.org/view.php?id=0000549)  - Please follow that link for details.
> Originally submitted on 2013-12-12 by mendor

I'm trying to use TOTALHOSTSERVICES\* macros. If I'm using one per command like ...!$TOTALHOSTSERVICESWARNING:host5$ everything works fine and I'm getting correct result, but if I'm using several per command like ...!$TOTALHOSTSERVICESWARNING:host6$,$TOTALHOSTSERVICES:host8$,$TOTALHOSTSERVICESUNKNOWN:host4$ or in host group form ...!$TOTALHOSTSERVICESCRITICAL:host_group:+$ results become incorrect (seems like in this case I'm getting all the info for the first mentioned host - host6 in my example).

several examples how I'm using those macros:

This one works:

```
define service{
use generic-service
host_name host2
service_description Test
check_command check_nrpe!check_test!$HOSTLATENCY:host_group:,$
max_check_attempts 3
servicegroups SG
}
```

output: `0.015,0.012,0.012,0.007,0.008,0.011,0.007,0.005,0.009`

This one doesn't work:

```
define service{
use generic-service
host_name host2
service_description Test
check_command check_nrpe!check_test!$TOTALHOSTSERVICESCRITICAL:host_group:,$
max_check_attempts 3
servicegroups SG
}
```

output: `0,0,0,0,0,0,0,0,0` - wrong output, I have some critical services on some of the hosts

This one works:

```
define service{
use generic-service
host_name host2
service_description Test
check_command check_nrpe!check_test!$TOTALHOSTSERVICESCRITICAL:host4$
max_check_attempts 3
servicegroups SG
}
```

output: `1` - correct output

This one doesn't work again:

```
define service{
use generic-service
host_name host2
service_description Test
check_command check_nrpe!check_test!$TOTALHOSTSERVICESCRITICAL:host4$,$TOTALHOSTSERVICESCRITICAL:host6$
max_check_attempts 3
servicegroups SG
}
```

**Comment by jfrickson** [comment]
Though the macro list in the documentation (https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/macrolist.html) puts them under `Host Macros`, the `TOTALHOSTSERVICES*` actually belong in the `Summary Macros` section.

Since summary macros have multiple macros grouped together, they are only populated once. For example, you might have: `$TOTALHOSTSERVICESOK$,$TOTALHOSTSERVICESWARNING$,$TOTALHOSTSERVICESCRITICAL$`. All the values would be populated when `$TOTALHOSTSERVICESOK$` is processed. When `$TOTALHOSTSERVICESWARNING$` is processed, the values are already there, so it doesn't have to look them up.

So, if you have `$TOTALHOSTSERVICESCRITICAL:host1$,$TOTALHOSTSERVICESCRITICAL:host2$` it populates the values for host1. Then when it goes to populate the values for host2, it sees the values have already been populated, and just returns, so the values for host2 are the same as for host1.
