### ISSUE TITLE
Backslashes disappear

### ISSUE THREAD

**Issue by Harbie34** [NagiosEnterprises/nagioscore#21]
When plugins output includes backslashes, disappear from status information. Is this by design?

e.g. check_disk_smb

	Disk ok - xxG(xx%) free on \\192.0.2.1\share
	-> Disk ok - xxG(xx%) free on \192.0.2.1share

**Comment by tmcnag** [comment]
It's by design, but maybe not our design.  Two backslashes like that are a type of [Escape Sequence](http://www.dummies.com/how-to/content/c-language-escape-sequences.html).

Since they have a lot of legitimate uses (like providing newlines, tabs, quotes, etc.) we don't make assumptions about how they should be used.  If you need two literal backslashes in a row, you would need to use `\\\\`.  But keep in mind, this would not work in the context of input to a plugin, since then you would be checking `\\\\192.0.2.1\\share`.  Sort of a "Can't have your cake and eat it too" situation.  A good plugin will detect this and escape the output properly.

This issue should be closed.
