### ISSUE TITLE
Error: Could not open log file

### ISSUE THREAD

**Issue by sdarwin** [NagiosEnterprises/nagioscore#303]
New issue on Nagios Core version 4.2.4

In the left web sidebar, go to Reports->Event Log

The message appears:

Error: Could not open log file '/usr/local/nagios/var/nagios.log' for reading!

This file has permissions 600
-rw-------  1 nagios nagios  4346 Dec 23 09:33 nagios.log

Perhaps from line 121 of nagioscore/base/logging.c opening the file with 600 permissions, as follows:

121         if ((fh = open(log_file, O_RDWR|O_APPEND|O_CREAT|O_NOFOLLOW, S_IRUSR|S_IWUSR)) == -1) {

 could this be modified to have the permissions as they were in previous versions of nagios?

-rw-r--r--  1 nagios nagios 78314 Jun 16  2016 nagios.log

That change was related to a security fix, however adding back merely "read" permissions for other users ought not be problem, as many sensitive files on linux are "readable".

**Comment by jrnash** [comment]
This is due to the web service not being able to read the log file, not
nagios.

Change ownership / permissions on the file to be the following so apache

-rw-r----- 1 nagios apache 4346 Dec 23 09:33 nagios.log

(apache or whatever your web server is)

**Comment by darylmonge** [comment]
Manually changing ownership will not address the root cause as log rotation and similar admin functions will simply have the permissions reset.  The underlying problem is the solution to CVE-2016-9566
Commit: ff22fd0de4938781edcbd48512d2494ca3c9c41a [ff22fd0]
Parents: bc90881490
Author: John C. Frickson <jfrickson@nagios.com>
Date: November 23, 2016 at 9:22:55 AM CST
which not only disables write access to eliminate the sym-link security problem but disables group read access to the "http" tools as well. 

I would propose adding S_IRGRP back to the "open" on line 121.  I don't think it will create the original security issue.

**Comment by sdarwin** [comment]
"S_IRGRP Read permission bit for the group owner of the file.", however the web service may not be in the group, so also "S_IROTH Read permission bit for other users." right? The previous permissions were 644.

**Comment by jfrickson** [comment]
I added `S_IRGRP`. The web service will be in the group. It has to be, or a lot of other things would fail.
Fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nagioscore/commit/7af89e5886192dfbbb28317ed2e4883ee92e13e0

**Comment by sdarwin** [comment]
"The web service will be in the group."
which group?  I am still getting the error. The web service is in the nagcmd group, however nagios.log is not. Overall, only a few files are assigned the "nagcmd" group, most are assigned to the plain "nagios" group.

**Comment by jfrickson** [comment]
That's what I get for rushing it. Sorry. Perms now set to 644 in maint branch. I'll maybe figure out how to make it more restrictive later.

**Comment by jgreen210** [comment]
For the benefit of distributions that need to backport this, this issue was fixed by this pair of commits:

7af89e5886192dfbbb28317ed2e4883ee92e13e0
d2481ed02e2ab64f83b6e9a43a65c74e791d343e

...which were released in nagios 4.3.0.
