### ISSUE TITLE
use_syslog doesn't seem to be working for me

### ISSUE THREAD

**Issue by kernow5000** [NagiosEnterprises/nagioscore#311]
In my config this is set to 0, however I still get messages in /var/log/messages I'm afraid. 

Nagios 4.2.4, CentOS 6.8 fully updated.

**Comment by jfrickson** [comment]
On my system, the only messages nagios sends to syslog are the "read() returned error 11" messages. Are those the ones you're talking about, or are there others?

**Comment by kernow5000** [comment]
Yeah just those.

**Comment by wooknight** [comment]
I have a similar issue , I have also set the log_file to a disk file but I get repeated messages in my log file as well as syslog

Feb 16 18:59:42 mon check_nrpe: Remote {IP} accepted a Version 2 Packet
Feb 16 18:59:42 mon check_nrpe: Remote {IP} does not support Version 3 Packets

**Comment by jfrickson** [comment]
There was a big issue a while back that I fixed. As part of that, we logged those `read() returned error 11` message. Initially they were logged with priority `LOG_ERR`. I recently downgraded that message to priority `LOG_NOTICE` so it would be easier to filter out. We may or may not get rid of them entirely in the future. But they do serve a purpose.

As for NRPE, syslog is currently the only log option. There is an open issue for nrpe to be able to log to a file instead of syslog, so that option will be coming. Those packet version messages are there to help you identify systems that are still running an older version of NRPE. They are logged with a priority of `LOG_DEBUG` so you should be able to filter them out.

Believe me, I _**know**_ how irritating it can be to have a lot of unnecessary messages filling the logs. I try to keep them to a minimum, and set the priorities appropriately.

So for now, I'll have to say that it's working as designed.

**Comment by douglasawh** [comment]
Additional info on "bug": https://support.nagios.com/forum/viewtopic.php?f=16&t=42885&p=214948#p214948
