### ISSUE TITLE
Compiling Nagios Core 4.2.4 on AIX 7.1 using gcc

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#326]
Detail provided at https://support.nagios.com/forum/viewtopic.php?t=42276&start=9999#bottom

**Comment by st-voss** [comment]
Some followup.
Calling check_completion without WNOHANG of course has a big disadvantage. A hanging monitor script would also block the nagios processes so I had to find another workarond for AIX's misbehaving wait4(). I tried using waitpid() instead of wait4()

```
*** ./lib/worker.c.ori  Sun Mar  5 12:04:31 2017
--- ./lib/worker.c      Sun Mar  5 12:07:21 2017
***************
*** 344,350 ****
         */
        do {
                errno = 0;
!               result = wait4(cp->ei->pid, &status, flags, &cp->ei->rusage);
        } while (result < 0 && errno == EINTR);

        if (result == cp->ei->pid || (result < 0 && errno == ECHILD)) {
--- 344,350 ----
         */
        do {
                errno = 0;
!               result = waitpid(cp->ei->pid, &status, flags);
        } while (result < 0 && errno == EINTR);

        if (result == cp->ei->pid || (result < 0 && errno == ECHILD)) {

```

Compiling was ok and nagios processes also started but I had many of the following entries in the nagios logfile despite none of the monitoring script were hanging:

[1488786254] wproc: Core Worker 7602268: job 1 (pid=20119788) timed out. Killing it
[1488786254] wproc: Core Worker 7602268: job 1 with pid 20119788 reaped at timeout. timeouts=1; st
arted=2
[1488786269] wproc: Core Worker 21692534: job 1 (pid=7733432) timed out. Killing it
[1488786269] wproc: Core Worker 21692534: job 1 with pid 7733432 reaped at timeout. timeouts=1; st
arted=2

I did some more debugging and found out that signal() was used instead of sigaction() in the enter_worker function in lib/worker.c. The default behaviour of signal() in AIX (and probably other plattforms) is to ignore further signals before calling the signal handler. So the SIGCHLD handler (which just increases "reapable" by 1) was called only once for every worker process.

Why was signal() used instead of sigaction() despite having "#define HAVE_SIGACTION 1" in include/config.h? Because lib/worker.c does not include include/config.h. So I had to use another patch:

```
*** lib/worker.c.ori    Fri Mar 10 12:16:17 2017
--- lib/worker.c        Fri Mar 10 12:17:30 2017
***************
*** 8,13 ****
--- 8,14 ----
  #include <time.h>
  #include <syslog.h>
  #include "libnagios.h"
+ #include "../include/config.h"

  #define MSG_DELIM "\1\0\0" /**< message limiter - note this ends up being
                             \1\0\0\0 on the wire as "" strings null-terminate */

```

With the above patch there are no more "reaped at timeout" messages and the worker processes were able to reap their child processes before reaching the timeout.

**Comment by jfrickson** [comment]
By changing `wait4()` to `waitpid()`, aren't you losing all the stuff in `struct rusage`?

**Comment by st-voss** [comment]
Yes, the information about the child processes' resource usage is lost by using `waitpid()` instead of `wait4()` but I wasn't able to see that this  `struct rusage` is referenced that much. 

Of course, it's not an ideal solution

**Comment by jfrickson** [comment]
I could probably wrap it in `#if` blocks. Should I check for `_AIX` or `_AIX51` or something else?

**Comment by st-voss** [comment]
Seems that wait4() has misbehaving on AIX for quite some time. Found references about it for AIX 5.2 from 2011.  So I would say check for `_AIX ` in the `#if ` blocks

**Comment by hedenface** [comment]
@jomann09 Are you able to test this by chance?

**Comment by hedenface** [comment]
Should be fixed in https://github.com/NagiosEnterprises/nagioscore/commit/dd20be73c7d9e80c0f70f3fbd8dc3b36654ccd29

I just went ahead and replaced all of the `wait3()` and `wait4()` calls with `waitpid()`.
