### ISSUE TITLE
Wildcard searching causes service status links to not work properly

### ISSUE THREAD

**Issue by heaje** [NagiosEnterprises/nagioscore#343]
Currently there appears to be a bug in the Nagios 4.3.1 UI when doing searches with wildcards.  As an example, here's what I did:

1. Use the search box in the navigation bar on the left side of the screen and search for something using a wildcard.  For instance, in this screenshot below, you can see I searched for "\*-prod-\*" and got back a set of hosts and their services.
![wildcard_search_1](https://cloud.githubusercontent.com/assets/3622298/23765204/ac1ef7e2-04bd-11e7-87c2-9f4cc519008d.png)

2. Click one of the links under the "Service Status Totals" heading at the top.  You will get a page that looks like this:
![wildcard_search_2](https://cloud.githubusercontent.com/assets/3622298/23765298/0245a922-04be-11e7-8cbc-3508a6067fb3.png)

The problem is exhibited by a permissions error.  I do have access to those hosts.  I have confirmed this in the cgi.cfg file.  Also, I'm the nagiosadmin user, so I have rights to everything anyway.  Things work properly if my search does NOT include a wildcard.  I can confirm this bug also exists in both Nagios 4.2.4 and 4.3.1.

**Comment by jfrickson** [comment]
This shouldn't be too hard to fix. I'll get on it.

**Comment by tjyang** [comment]
I confirm this issue in my 4.3.1 instance.

**Comment by raymonvdm** [comment]
When searching for `sol-prd*` i get this same issue. But searching for `sol*prd*` works. but this is because the name sol-prod is renamed bij nagios to sol_prd. So the sol-prod is not excisting. Nagios gives me the following warning but should tell me the object is not found


`

It appears as though you do not have permission to view information for any of the hosts you requested...
If you believe this is an error, check the HTTP server authentication requirements for accessing this CGI
and check the authorization options in your CGI configuration file.

`

**Comment by Dhyrule** [comment]
This error does indeed seem to result from not getting any results from the search.

**Comment by heaje** [comment]
@raymonvdm / @Dhyrule: Yes, I am 100% sure this is a search involving existing hostnames.  As seen in my screenshot, I can search for "\*-prod-\*" and get back results.  If I then try one of the links under the service totals, I then get the error I see.  I didn't change my search.  I just just clicked a link to look at a specific status across these hosts.

**Comment by jfrickson** [comment]
Fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nagioscore/commit/ce386aca332b3dd90103c5f71e75de38574d5775
