### ISSUE TITLE
CVE-2016-10089

### ISSUE THREAD

**Issue by douglasawh** [NagiosEnterprises/nagioscore#353]
https://nvd.nist.gov/vuln/detail/CVE-2016-10089

I know John is aware of this, but there doesn't appear to be anything on github about it for the customers that are asking about it to follow, so here it is.

**Comment by akien-mga** [comment]
This was closed, but was it fixed? If so, in what commit?

**Comment by hedenface** [comment]
I only closed this because I know it isn't the nature of John (jfrickson) to leave this kinds of things open for very long while he was working on this project.

If someone can point me to a proof of concept, or decipher the CVE (and ones mentioned therein) for me, I'd be glad to attempt to reproduce and determine where it was fixed it.

**Comment by akien-mga** [comment]
See https://bugs.mageia.org/show_bug.cgi?id=20050#c3 for an analysis and https://bugs.mageia.org/show_bug.cgi?id=20050#c7 for a patch proposal.

**Comment by hedenface** [comment]
Applied David Walser's patch in https://github.com/NagiosEnterprises/nagioscore/commit/ef690014b2944b87ab078a71b2e57d2179a6ae66.

My apologies. We just switched maintainers, and the previous one was rather good about doing things but not commenting/closing them so I made an unfair assumption.

It would be nice if someone could verify that this works?
