### ISSUE TITLE
Bogus log messages 'Unknown jobtype: 10' when using process_performance_data (service_perfdata_command/host_perfdata_command) 

### ISSUE THREAD

**Issue by abrist** [NagiosEnterprises/nagioscore#36]
Cross Post from Tracker:
http://tracker.nagios.org/view.php?id=534
Reporter: ovidiu_stanila 

When using service_perfdata_command or host_perfdata_command configuration Nagios logs a warning message for each service/host check. These warning messages look like:
[1383116400] Worker 1277: Unknown jobtype: 10
[1383116400] wproc: Unknown job type: 10
[1383116400] Worker 1279: Unknown jobtype: 10
[1383116400] wproc: Unknown job type: 10
[1383116400] Worker 1278: Unknown jobtype: 10
[1383116400] wproc: Unknown job type: 10

User Submitted patch:

http://tracker.nagios.org/file_download.php?file_id=205&type=bug

**Comment by shashikanthbussa** [comment]
How to apply bogus_warnings.patch on the existing nagios setup.

Where we customized the nagios configuration files and Host and commands as per the organization needs. If wee run install from the new source does it not going to effect or replace the exiting files ?.

In case to  keep the exiting setup as usual and apply the patch. What needs to be done

**Comment by tmcnag** [comment]
In regards to accepting this patch, it looks like there was enough feedback in the Tracker report to indicate that it does not cause any harmful side-effects.  Pending developer input, I suggest accepting the patch.

@shashikanthbussa - Not knowing anything about how you installed in the first place, my suggestion would be to back up your configs before applying the patch and recompiling.

**Comment by shashikanthbussa** [comment]
I already applied the patch successfully. I never thought this much time for supporting my question.

**Comment by tmcnag** [comment]
Apologies for the delay, though I am going through all of the open issues and either fixing, commenting, or requesting more info from all of them in order to keep this sort of delay from happening.

It is also worth noting that our official support forum is a more appropriate place to get help:

http://support.nagios.com/forum/viewforum.php?f=7

Our support staff (myself included) are on the forums during business hours and would be happy to help with any questions going forward.  As it stands right now, the GitHub pages are not part of our daily support workflow, so the forums are a much safer bet if you have questions.

**Comment by jfrickson** [comment]
Fixed in commit: https://github.com/NagiosEnterprises/nagioscore/commit/fdcf340ffa4157e1a4646e9b149760c2ac223e58
