### ISSUE TITLE
Error on nagios upgrade to 4.3.3

### ISSUE THREAD

**Issue by jogendrajangid1** [NagiosEnterprises/nagioscore#416]
Hi Team,
I have upgrade Nagios 4.3.3 from 4.3.2 I'm getting below error on service restart/reload.
`ERROR: Could not create or update '/usr/local/nagios/var/nagios.configtest`
`touch: cannot touch ‘/run/nagios.lock’: Permission denied`(I have added acl then it is working.)

And How can I configure Nagios to avoid host services alert on the host down?

**Comment by hedenface** [comment]
The `/run/nagios.lock` was just fixed in the maint branch - it will be resolved in 4.3.4 (coming very very soon). - but you can also override the value by running configure with --with-lockfile= such as:

```
./configure --with-lockfile=/var/run/nagios.lock
```

Or some other appropriate location of your choosing.

You can adjust your host and service notification options in their definitions in order to avoid notifications when they reach a down state.

**Comment by hedenface** [comment]
I'm gonna close this - as the bug portion has been fixed. Feel free to continue the thread, though :)

**Comment by Raptus1** [comment]
I get the same error without the touch part:

> Oct 10 15:17:50 systemd[1]: Starting LSB: Starts and stops the Nagios monitoring server...
> Oct 10 15:17:50 su[28095]: Successful su for nagios by root
> Oct 10 15:17:50 su[28095]: + ??? root:nagios
> Oct 10 15:17:50 su[28095]: pam_unix(su:session): session opened for user nagios by (uid=0)
> **Oct 10 15:17:50 nagios[28089]: Starting nagios:ERROR: Could not create or update '/usr/local/nagios/var/nagios.configtest'**
> Oct 10 15:17:50 systemd[1]: nagios.service: Control process exited, code=exited status=8
> Oct 10 15:17:50 systemd[1]: Failed to start LSB: Starts and stops the Nagios monitoring server.
> Oct 10 15:17:50 systemd[1]: nagios.service: Unit entered failed state.
> Oct 10 15:17:50 systemd[1]: nagios.service: Failed with result 'exit-code'.


It worked fine before upgrading to 4.3.4...

**Comment by wu-andrew** [comment]
he resolution to this problem is to remove the /usr/sbin/nologin directive from the passwd file, or to define it as a valid shell. The following examples should resolve the problem (depending on your operating system):

No shell defined:

nagios:x:1001:1001::/home/nagios:
 

Bash shell defined:

nagios:x:500:500::/home/nagios:/bin/bash
 

Once you have updated the passwd file you will be able to successfully start the nagios service.
https://support.nagios.com/kb/article/nagios-core-error-could-not-create-or-update-nagios-configtest.html
