### ISSUE TITLE
Host stuck in soft state after I changed max_check_attempts and reloaded.

### ISSUE THREAD

**Issue by thepony100** [NagiosEnterprises/nagioscore#427]
I currently have nagios version 4.3.4. 
I found that host would stuck in (DOWN) soft state and check attempt would not increasing after I set my max_check_attempts below current check attempt. 

![untitled](https://user-images.githubusercontent.com/24579891/30311480-9fd94b50-97bf-11e7-9126-5567fccf9f0d.png)

I think it should go into DOWN hard state. But it didn't. It stayed like this with no notification send out because it's in soft state.  Until host went up again, and status was returned to normal. 

You can replicate this by doing these step.
First, set max_check_attempts to 10 or more for host "test" and then shut down host "test".
Then, wait for Nagios to check host "test" and go into (DOWN) soft state. wait more for 3 or 4 retry.
And then change max_check_attempts to 2 or any number below current attempts. restart Nagios.
It will stuck in that state until the host goes up again.

**Comment by hedenface** [comment]
Well ..I'm not sure what the question or problem is here. You're describing it exactly how it is designed to work. max_check_attempts means exactly that - the max amount of times the check is performed.

If you aren't using retention data, this problem should go away since Nagios wouldn't know how many checks deep it was after the restart.
