### ISSUE TITLE
Nagios Core doesn't handle properly services with a dollar sign in the name

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nagioscore#459]
When there is a dollar sign in the service name, Nagios Core "thinks" it is a macro, and appends "$" at the end of the output, breaking the check. This was tested with check_ncpa.py in Nagios Core 4.3.4.

Running the check from the command line works:

`./check_ncpa.py -H x.x.x.x -t 'mytoken' -M 'services' -q 'service=my$service,status=running'`
`OK: my$service is running`

However, in the GUI, you see an error:

`CRITICAL: my$service is running (should be running$)`

This is a sample (partial) service definition:

`define service {`
	`host_name			myhost`
	`service_description		myservice`
	`check_command			check_xi_ncpa!-t 'mytoken' -P 5693 -M 'services' -q` `'service=my$service,status=running'`
	`...`
	`}`

In the nagios.debug log you see something like this:

`[1512761269.949232] [2048.1] [pid=32953] Processing: '-t 'mytoken' -P 5693 -M 'services' -q 'service=my$service,status=running''`
`[1512761269.949233] [2048.2] [pid=32953]   Processing part: '-t 'mytoken' -P 5693 -M 'services' -q 'service=my'`
`[1512761269.949235] [2048.2] [pid=32953]   Not currently in macro.  Running output (67): '-t 'mytoken' -P 5693 -M 'services' -q 'service=my'`
`[1512761269.949242] [2048.2] [pid=32953]   Non-macro.  Running output (67): '-t 'mytoken' -P 5693 -M 'services' -q 'service=my'`
`[1512761269.949244] [2048.1] [pid=32953]   Done.  Final output: '-t 'mytoken' -P 5693 -M 'services' -q 'service=my$service,status=running'$'`

**Comment by hedenface** [comment]
Fixed in https://github.com/NagiosEnterprises/nagioscore/commit/628ddd0349e9c84f46a46f3672f86e5977514d7b

Thanks @ludmilmm  and @jomann09  !

**Comment by hedenface** [comment]
Better fix here. https://github.com/NagiosEnterprises/nagioscore/commit/6e03fe6c6b2da518dbbf41f4ca1803cc6a695c05

The docs explain that using a dollar sign in your string requires you to use 2 of them. The bug officially is that as it replaces the macro, it is putting another $ on the end that it shouldn't be. Given the check_command provided: 

`./check_ncpa.py -H x.x.x.x -t 'mytoken' -M 'services' -q 'service=my$service,status=running'`

I think even if you did something like this:

`./check_ncpa.py -t 'mytoken' -M 'services' -q 'service=my$service,status=running' -H $HOSTADDRESS$`

The last macro won't finish either - simply because of the way it tokenizes. The proper way to handle that would obviously be: 

`./check_ncpa.py -t 'mytoken' -M 'services' -q 'service=my$$service,status=running' -H $HOSTADDRESS$`

As the $$ doesn't just quote it for bash, it also allows the macro parsing to tokenize properly. I'll take a ***quick*** look to see if resolving that is easy - otherwise we'll just have to stick to documented protocol.

**Comment by hedenface** [comment]
Yeah. It wouldn't be quick. It would require an entire rewrite of the process macros function. No dice.
