### ISSUE TITLE
[PATCH] Too small number of workers is created

### ISSUE THREAD

**Issue by cejkar** [NagiosEnterprises/nagioscore#49]
Please see #667 in Mantis, the patch is included here.

**Comment by tmcnag** [comment]
Link for reference:  http://tracker.nagios.org/view.php?id=667

**Comment by jfrickson** [comment]
Fixed in branch nagios-maint with commit https://github.com/NagiosEnterprises/nagioscore/commit/8f8549f3f04e48a72dea6805d7067a37f79b7bfc

Doing some research, the consensus is that there is seldom a reason to set backlog to a small number. So I used code similar to what was used in TOR -- start with INT_MAX and fall back to SOMAXCONN if INT_MAX fails.

Fixed for issues
http://tracker.nagios.org/view.php?id=667
https://github.com/NagiosEnterprises/nagioscore/issues/49
https://github.com/NagiosEnterprises/nagioscore/issues/51
