### ISSUE TITLE
Increase socket queue lenght on nagios

### ISSUE THREAD

**Issue by djadk84** [NagiosEnterprises/nagioscore#51]
Im running FreeBSD 10.1 I have install nagios 4.0.8, I found that max queue length is very low in freeBSD value is set to 3. I was getting some error alert that made it nagios unreliable I was able to fix the problem by increasing the max queue length or make it a setting variable. below is the ticket I have opened with nagios support with more detail.
http://support.nagios.com/forum/viewtopic.php?f=7&t=33274&p=141728#p141728

**Comment by djadk84** [comment]
Best approach would be to make it like nginx and bsd's OS. Take a look on their docs and see.
http://nginx.org/en/docs/http/ngx_http_core_module.html

**Comment by dbarr** [comment]
FreeBSD ports actually patches this already:

https://github.com/freebsd/freebsd-ports/blob/master/net-mgmt/nagios4/files/patch-lib_nsock.c

**Comment by djadk84** [comment]
I'm currently running pkgsrc on freebsd not port tree also I think it better if upstream solve this by making this value same as the max socket connection allowed.

**Comment by jfrickson** [comment]
Issue https://github.com/NagiosEnterprises/nagioscore/issues/49 is for the same problem. I will probably apply the same fix that was done to NRPE.

**Comment by jfrickson** [comment]
Fixed in branch nagios-maint with commit https://github.com/NagiosEnterprises/nagioscore/commit/8f8549f3f04e48a72dea6805d7067a37f79b7bfc

Doing some research, the consensus is that there is seldom a reason to set backlog to a small number. So I used code similar to what was used in TOR -- start with INT_MAX and fall back to SOMAXCONN if INT_MAX fails.

Fixed for issues
http://tracker.nagios.org/view.php?id=667
https://github.com/NagiosEnterprises/nagioscore/issues/49
https://github.com/NagiosEnterprises/nagioscore/issues/51
