### ISSUE TITLE
bug in event broker callbacks during Nagios startup

### ISSUE THREAD

**Issue by scottwilkerson** [NagiosEnterprises/nagioscore#591]
From here: https://support.nagios.com/forum/viewtopic.php?f=34&t=50981

I'm looking at Nagios 4.4.2 code.

main() calls daemon_init() [base/nagios.c, line 614] which in turn
calls broker_program_state() [base/utils.c, line 2026] to make a
NEBTYPE_PROCESS_DAEMONIZE callback. But all of that now happens before
neb_init_callback_list() ever gets called [base/nagios.c, line 667],
let alone any event brokers having been loaded via neb_load_all_modules()
[base/nagios.c, line 708]. So at the time of the call to daemon_init(),
no event broker init functions have yet been called so they could register
to receive the NEBTYPE_PROCESS_DAEMONIZE callback.

It's clear in comparison to Nagios 3.5.1 files that this failure is
due to a bunch of code having been shuffled around, without recognizing
this consequence.

**Comment by Madlohe** [comment]
So the "offending" change was https://github.com/NagiosEnterprises/nagioscore/commit/df6b2e53c790ec010497c4f59e6dc50e6f46ff85

which seems to have done this almost-intentionally.

The real question is "Are there any NEB modules which actually use this callback?" I'm guessing the answer is "no," since this was only found by someone looking for a different bug. Will look more into this tomorrow, though.

**Comment by Madlohe** [comment]
I wasn't able to find any modules which used this callback. Since it (most likely) hasn't been working for ~7 years, I've removed it.
