### ISSUE TITLE
Stalking notification functionality not working

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/nagioscore#604]
This was implemented but it's not currently working (tested on 4.4.2 and 4.4.3rc1):

https://github.com/NagiosEnterprises/nagioscore/issues/342

> As of Core 4.4.0 if stalking was triggered then a NOTIFICATION will be sent if the N option is defined.

Taken from this page:

https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/stalking.html

**Comment by jomann09** [comment]
So the first part of this bug is that setting N forces the host/service to log the state every time Core decides that it has to check if its sending a notification, which isn't intended by #342 or intended by the option itself.

What I did:
I fixed the N option to only log when a notification goes out.

What I will add for later:
I am going to basically create a new issue here that references this and the other one for the addition of a host/service option that is something like `stalking_notify` where we would send a notification if any stalking option is triggered (besides the N option of course)

**Comment by jomann09** [comment]
Closing this, the new option is in the referenced issue linked to this issue.

I have updated the Core docs with the new wording for how the new` N` stocking option works.
