### ISSUE TITLE
Blank Screen on Nagios Web UI v4.4.3 -- Bug 

### ISSUE THREAD

**Issue by rosri1992** [NagiosEnterprises/nagioscore#628]
Hello, 
I have installed latest version of Nagios on EC2 Instance. So When I trigger a custom Alert, or Trigger a next check from nagios web UI, Some time I see the Blank Screen, and after some time like 5min, I get the option to hit commit button of that alert/service check. 
Adding the screenshot too. 
![Nagios-erro](https://user-images.githubusercontent.com/48814564/55508649-4fdbdb80-5628-11e9-8b67-a51a5943ddcd.PNG)

Let me if this a bug or not

**Comment by Madlohe** [comment]
Hi @rosri1992,

I don't think that's expected behavior. When you have this issue, do you see any messages in the logs? Do you see any errors in your browser console?

Also, if you have support issues like these, you will most likely get a faster response by visiting our [support forums](https://support.nagios.com/forum/viewforum.php?f=7). The General Support section is free to use, and you will usually get a technician's response within ~24 business hours.

**Comment by rosri1992** [comment]
You can close this ticket
