### ISSUE TITLE
How to Combine SG & HG in Nagios Core 4.4.3

### ISSUE THREAD

**Issue by rosri1992** [NagiosEnterprises/nagioscore#636]
I'm trying to define servicegroup for a service (CPU load) for a group of host which are in Host group. But I couldn't add a HG in memeber.  I defined the SG as below:

define servicegroup{
       servicegroup_name        Testing-CPU-load-SG
       alias                   Metrics-Monitoring
       members           CPU-load (Service name), XXXX(HG)
}

Let  me know if it is wrong.

**Comment by ericloyd** [comment]
Hostgroups can't be added to service groups, only services.  But I think this (https://support.nagios.com/forum/viewtopic.php?f=6&t=40187) may be related.  Services assigned to hostgroups can't then be assigned to servicegroups because the parser doesn't have the end state configuration yet when it tries to parse if valid services are assigned to servicegroups.

**Comment by Madlohe** [comment]
Thanks for the assistance @ericloyd. Closing this now.
