### ISSUE TITLE
Semi-colons in check results output are turned into colons

### ISSUE THREAD

**Issue by jomann09** [NagiosEnterprises/nagioscore#652]
More details on this here https://github.com/NagiosEnterprises/nrdp/issues/40 if you create the file below in `/usr/local/nagios/var/spool/checkresults` it will change the `;` to `:` when it reads it and parses it.

The example file, you can also run command in the issue linked above.
```
### NRDP Check ###
start_time=1560978379
# Time: Wed, 19 Jun 2019 16:06:19 -0500
host_name=localhost
service_description=PING
check_type=1
early_timeout=1
exited_ok=1
return_code=2
output=OK: result1=1; result2=2;\n
```

**Comment by Madlohe** [comment]
Finally got around to this.

checks.c, lines 799-806:
```

	/* make sure the plugin output isn't null */
	if (svc->plugin_output == NULL) {
		svc->plugin_output = (char *)strdup("(No output returned from plugin)");
	}
	/* otherwise replace the semicolons with colons */
	else {
		replace_semicolons(svc->plugin_output, temp_ptr);
	}
```
This looks intentional, so I'm assuming this is escaping something important (hopefully not bash injection, but maybe something is semicolon-delimited somewhere?). That logic goes back to 2002, but the comments/commit messages around it don't say why the semicolon-replacement is important.

**Comment by Madlohe** [comment]
Continued looking through the code & related support tickets. It seems like changing this potentially impacts performance data processing and serialization for a couple of CGIs. The behavior seems to be consistent for passive/active checks, so we're not going to change this (at least for now).
