### ISSUE TITLE
Last Check timestamp is not shown for passive checks

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/nagioscore#659]
Last Check timestamp is not shown for passive checks in Nagios Core 4.4.3. "NA" is shown instead. This used to work in older versions of Nagios Core.

![example01](https://user-images.githubusercontent.com/1896530/61383750-e6997480-a874-11e9-8648-5abea3f24b71.PNG)

Let me know if you need any additional information to troubleshoot the issue, e.g. logs, configs, etc.

**Comment by ericloyd** [comment]
Yes.  Agree.  Concur.  We just starting troubleshooting an issue on 5.6.4 (upgraded from 5.5.6) and noticed this same thing.  Especially when combined with freshness checking, this can get confusing.

**Comment by ericloyd** [comment]
Sorry - I need to ask - we have a customer relying on freshness checks that is complaining that because of this NA date, the checks are saying that they're thousands of days stale and the freshness check is triggering every time.

Is this patch out for XI installations yet?  I know it's an NRDP thing, but the checks are submitted via send_nrdp, so we need to get this installed pronto.

**Comment by Madlohe** [comment]
5.6.5 (with NRDP 2.0.2) will be released at some point this afternoon.

**Comment by ericloyd** [comment]
Thanks!
