### ISSUE TITLE
Memory leak when using event broker

### ISSUE THREAD

**Issue by gzalo** [NagiosEnterprises/nagioscore#664]
Hi.  I've found a memory in run_async_service_check and run_async_host_check, when using event brokers (in my case mod_gearman 3.10). If lots of checks per second are running, this can leak a couple of GBs per day.

![3.1.0 leak](https://i.imgur.com/EOsLvcX.png)

https://github.com/NagiosEnterprises/nagioscore/blob/a7346f7d630813536ff42f7daa8ad2afd24139f4/base/checks.c#L3186-L3193

The calloc'd variable "cr" (which contains the tentative check results) has its contents cleared but is never free'd. 
When using mod-gearman, the memory for the check results is allocated when the results of a check are ready, and thus the memory allocated by Nagios itself will leak. 
There is no way to free it on the NEB module without making the nagios process crash when it calls free_check_result, since the module can't set the cr variable to null (it will keep pointing to recently free'd memory).

Thanks, Gonzalo

**Comment by Madlohe** [comment]
Thanks for reporting this! I'll try to look into this sometime this week.

**Comment by Madlohe** [comment]
Okay, I had time to look at this.

It looks like `free_check_result` does not free the `cr *` itself, because in some places this struct is allocated on the stack. Elsewhere in the program, free_check_result() is followed by freeing the pointer separately. 

I've set up a branch at https://github.com/Madlohe/nagioscore/tree/bug-664/leaky-MG-check-results which seems to be working. Would you be willing to compile from there and verify that this fixes the issue for you?

**Comment by gzalo** [comment]
> Would you be willing to compile from there and verify that this fixes the issue for you?

Sure, I will be testing it today. I will keep you posted once I test it. Thanks a lot!

**Comment by gzalo** [comment]
It appears to be working fine, the memory leak is gone! Thanks

**Comment by Madlohe** [comment]
Excellent! Merging and closing now.
