### ISSUE TITLE
Question : Nagios/NagiosXI : Is there any plan to release container version?

### ISSUE THREAD

**Issue by ranjithkodumbu** [NagiosEnterprises/nagioscore#710]
Hi Team,

Is there any plan to release Nagios core/XI on docker container, so that we can scale out easily? I understand that there are challenges to put it on container; but I am curious to know the answer. So that I can think of whether to continue with NagiosXI/move to other tool as this is one of my client requirements.

Thanks,
Ranjith Kumar

**Comment by ericloyd** [comment]
626 results on Docker hub.  https://hub.docker.com/search?q=nagios&type=image

Personally, I don't think making Nagios into a Docker container makes much sense.  It's very light weight on a VM, can run in most normal OS's under Virtualbox or Hyper-V without needing full-blown VM infrastructure, may require a number of ports to be exposed (NSCA, SSH, NCPA, NRPE, HTTP, HTTPS, etc), and most importantly, becomes a bear to manage without persistent storage.

So why not use -v when running the docker container, you ask?  If you're going to do that with configs, logs, RRD files, plugins, and so forth, then you're basically devoting your system resources to providing virtual resources inside the container, which means you might as well just run the Nagios code on the real system in the first place rather than trying to containerize it.

I'm not against the idea, I'm just not sure what it brings to the table in the real world outside of a lab or Proof-of-concept.  Most of our customers aren't going to containerize their monitoring, they're going to monitor their containers.  Nagios (especially XI) doesn't do well in a small room with no windows.  It works much better when it can integrate with the rest of the world.  

So sure, make a Docker container for Nagios so you can run it and see what it does.  But when the time comes to run Nagios in production, it's going to essentially take over the machine the container is running on to grant persistent storage and external access points anyway, so why not just devote a [virtual or otherwise] slice to it and let it run for real?

**Comment by ranjithkodumbu** [comment]
The idea for containerize has many benefits like easy upgrade/scale out to
lakhs of service checks/to ensure the availability of monitoring
system/when capacity issue arises Just add one worker node to backend/easy
management/in single nagios console can view all nodes and services etc.

Regards,
Ranjith Kumar

**Comment by ericloyd** [comment]
I agree that it scales in a particular way, but it doesn't scale in others.  At the current state of containerization, after having done hundreds of Nagios installations for customers small and large, it is my opinion that a VM (or dedicated machine) is still the preferred way to deploy Nagios at this time.

Your use case may vary, and as I wrote in my reply, there are over 600 Nagios related Docker images on the Docker hub.  You may wish to start there to find someone who has done the work already and see how it works for you.

I'd rather Nagios Enterprises spend its limited development efforts on fixing bugs, updating Nagios Core to a 21st Century modular/object-oriented design, and solidifying Enterprise-class features rather than worry about deployment efforts.  But again - that's my opinion.

**Comment by sawolf** [comment]
Hi @ranjithkodumbu,

Yes, there are tentative plans to make Core/XI scalable via docker/kubernetes. It'll require significant rearchitecture of the application, so don't expect it any time soon, but we're well aware of the benefits it could bring for larger deployments.

**Comment by ranjithkodumbu** [comment]
Hi Sebastian, Good to hear.

Thanks for the update.

Regards,
Ranjith Kumar R

**Comment by ranjithkodumbu** [comment]
There are other monitoring tools available like Sensu, Pandrora fms etc
