### ISSUE TITLE
Nagios agent crashing with segfault error

### ISSUE THREAD

**Issue by devopstrainer1** [NagiosEnterprises/nagioscore#713]
We are currently using Nagios 4.1 and we are seeing nagios process frequently crashing with below mentioned error, any help or suggestion on how to mitigate this issue:-

segfault at 0 ip 00007f1f1a175bba sp 00007fff43cf0400 error 4 in libc-2.12.so[7f1f1a015000+18b000]

**Comment by ericloyd** [comment]
There is no single Nagios agent.  Are you referring to the Nagios process itself, or the NRPE client or the NCPA client or NSclient++ or something else?

**Comment by devopstrainer1** [comment]
the nagios process itself, on nagios management server

**Comment by ericloyd** [comment]
The last version of Nagios Core 4.1 was 4.1.1, released on August 19, 2015.  First, our primary suggestion is to upgrade to Nagios Core 4.4.5, which was released August 20, 2019.  

Second, without knowing more about your system (such as memory, CPU, and what you're doing with Nagios), it's hard to say.  I really think you need to upgrade your software though, because not only is your Nagios Core 4 years old, but your glibc (v2.12) was released December of 2010 - that code is almost 9 years old now.

I realize updating your system may not be an option, but I strongly suggest that if you can do so, please do that first.

**Comment by sawolf** [comment]
I agree with @ericloyd - if the process is segfaulting, a code change is usually the best fix (meaning you'll need to update Nagios Core anyways). If you still see this issue on Core 4.4.5 let me know and we can determine next steps.
