### ISSUE TITLE
 Retry_interval not respected for host checked with nagios 4.4.3 

### ISSUE THREAD

**Issue by ladis-washerum** [NagiosEnterprises/nagioscore#755]
Hi, 

The version 4.4.2 have resolved the problem about retry_interval but sometimes we have again this problem.
This issue who we have seems similar at this one :

"Nagios not using retry_interval for service in SOFT state unless host is also down #551"

The time between the soft state and the hard state is just 15 secondes.
For information, we have this problem when nagios excute an host check on-demand, when a service associated with the host changes state. 

Host Down[08-04-2020 08:52:50] HOST ALERT: **-**-**;DOWN;HARD;2;PING CRITICAL - 5 packets transmitted, 0 received, 100% packet loss, time 4004ms

Host Down[08-04-2020 08:52:35] HOST ALERT: **-**-**;DOWN;SOFT;1;PING CRITICAL - 5 packets transmitted, 0 received, 100% packet loss, time 3998ms

Service Critical[08-04-2020 08:52:21] SERVICE ALERT: **-**-**;CPU;CRITICAL;SOFT;1;CRITICAL - Plugin timed out while executing system call

Service Critical[08-04-2020 08:52:19] SERVICE ALERT: **-**-**;POWER_SUPPLY_2;CRITICAL;SOFT;1;CRITICAL - Plugin timed out while executing system call

This is my configuration for the host :
Check Interval --> 0h 5m 0s
Retry Interval --> 0h 2m 0s
Max. Check Attempts --> 2

Can you help me please.

Thanks in advance.

**Comment by sawolf** [comment]
Hi @ladis-washerum,

I'm having a bit of trouble understanding the post, my apologies if I misinterpret anything you've said here.

First, you mention that you had an issue that was solved in 4.4.2. Can you provide a link to that issue?

I don't think #551 is related to what you're describing - the user was seeing that service checks were rescheduled using their normal check_interval rather than their retry_interval.

1.) You have a host check configured and running normally.
2.) When the host was soft down, you performed an on-demand check (using the button labelled "Re-schedule the next check of this host")
3.) The host became hard down immediately after the on-demand check.

If this is correct, that's also the expected behavior of nagios core. The retry_interval is only used to determine the internal scheduling for nagios. It doesn't interact with user-generated check scheduling.

**Comment by ladis-washerum** [comment]
Hi @sawolf 
Thank you for your answer. 

We apologise if we gave an issue number that is not really related with our problem. 

We will try to explain it differently: 
- All our hosts are configured like this : 
Check Interval --> 0h 5m 0s
Retry Interval --> 0h 2m 0s
Max. Check Attempts --> 2
- All our services are configured like this : 
Check Interval --> 0h 5m 0s
Retry Interval --> 0h 2m 0s
Max. Check Attempts --> 3
- We didn’t do any manual action : the logs we gave are the result of the Nagios scheduler only 

In our example, we had a network issue during 2 minutes. We can see that some services became critical soft. Nagios issued an on-demand check on the host (as described in Nagios Host Check documentation). The host became down soft. Then, 15s later, the host became down hard. So the retry interval was not respected. 

To answer you more precisely: 
1) you are right 
2) no, we didn’t do any manual action 
3) the host became down hard 15s after the down soft 

We hope things are clearer now :) 

Thank you for helping !

**Comment by sawolf** [comment]
Thanks for clarifying!

Is this something you're able to reproduce consistently, or an event that has only happened once (or is it somewhere in-between)?

If you can reproduce it consistently, let me know what you do to set up the problem. Host/service configurations are preferred, but if you do anything else abnormal, that would also be good to know.

If not, I'll try to look into it soon, but it's unlikely I'll be able to resolve it with the information that I have.

**Comment by ladis-washerum** [comment]
Hi, 

This event has happened several times.
We will try to reproduce them and if we are successful we will give you the log of the incident with the all details and the Hosts/services configuration  which we will have.

We try to give you a feedback, soon as possible.

Thanks for your support.
