### ISSUE TITLE
PHP vulnerability issues in Nagios Core 4.4.4 version

### ISSUE THREAD

**Issue by vipinvgeorge** [NagiosEnterprises/nagioscore#761]
Hi all,

My security team reported PHP vulnerability issues in my nagios core 4.4.4 version. PHP version is PHP 5.4.16,  Can this be upgrade to the any latest PHP versions ? Please advise.

# php -v
PHP 5.4.16 (cli) (built: Oct 29 2019 10:01:20)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

# httpd -v
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   Jun  9 2019 13:01:04

bash-4.2$ uname -a
Linux lrkxxxxp03 3.10.0-1062.18.1.el7.x86_64 #1 SMP Wed Feb 12 14:08:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
bash-4.2$

nagios@lrkxxxxp03 [/home/nagios]
$ /usr/local/nagios/bin/nagios –help

 Nagios Core 4.4.4
Copyright (c) 2009-present Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
Last Modified: 2019-07-29
License: GPL

**Comment by sawolf** [comment]
For CentOS/RHEL, version numbers don't necessarily indicate a vulnerable package, due to their [backporting policy](https://access.redhat.com/security/updates/backporting). If you find a specific vulnerability, please create a new issue or forum post or support ticket with a proof of concept. Thanks!
