### ISSUE TITLE
Escalation process message and port number

### ISSUE THREAD

**Issue by Jason-MK** [NagiosEnterprises/nagioscore#832]
Hello,

I'm using Nagios core 4.4.6 and I did manage to receive escalation notifications but the problem is that I received for the escalation the same content of the normal alert content means I need to specify at least one word in the escalation notification that shows this an escalation mail not a normal mail .

This is what I have in the commands.cfg for the notifications for both service and host

`define command {

    command_name    notify-host-by-email
    command_line    /usr/bin/printf "%b" "***** Nagios *****\n\nNotification Type: $NOTIFICATIONTYPE$\nHost: $HOSTNAME$\nState: $HOSTSTATE$\nAddress: $HOSTADDRESS$\nInfo: $HOSTOUTPUT$\n\nDate/Time: $LONGDATETIME$\n" | /usr/bin/mailx -s "** $NOTIFICATIONTYPE$ Host Alert: $HOSTNAME$ is $HOSTSTATE$ **" $CONTACTEMAIL$
}

define command {

    command_name    notify-service-by-email
    command_line    /usr/bin/printf "%b" "***** Nagios *****\n\nNotification Type: $NOTIFICATIONTYPE$\n\nService: $SERVICEDESC$\nHost: $HOSTALIAS$\nAddress: $HOSTADDRESS$\nState: $SERVICESTATE$\n\nDate/Time: $LONGDATETIME$\n\nAdditional Info:\n\n$SERVICEOUTPUT$\n" | /usr/bin/mailx -s "** $NOTIFICATIONTYPE$ Service Alert: $HOSTALIAS$/$SERVICEDESC$ is $SERVICESTATE$ **" $CONTACTEMAIL$
}`

On the host itself this what I have for the escalation settings

`define serviceescalation {

    host_name                       Test
    service_description             Check SSH
    first_notification              3
    last_notification               5
    notification_interval           20
    contact_groups                  MGMT
}`

Another question how to monitor an IP with a port number for example I have Grafana with this IP 192.168.60.120:2000

Which content should I add to Grafana.cfg so I can monitor the IP and Port number ?

Best Regards

**Comment by sawolf** [comment]
This is probably a much later response than you were looking for, but:
1) For escalations, there is a macro $NOTIFICATIONISESCALATED$ which returns 1 if the check was escalated and 0 otherwise. I think the mindset for the implementation was that you'll know the check was escalated because you don't normally get e-mails for that check. However, that assumes that the notification's receiver knows about nagios and expects to receive escalated notifications automatically, which isn't always true in practice.

If you need to change actual text based on $NOTIFICATIONISESCALATED$, I would recommend adding a new command that does a little extra legwork in changing macros to text. i.e. you can wrap the existing printf line in a bash script (the bash script goes wherever your other nagios plugins live), but parse the macros individually and use them to generate the string that gets written via printf.

2) For the grafana monitoring, if you just need to monitor that you can connect to a port, you can use check_tcp from nagios-plugins. If you need to actually get metrics related to grafana, that isn't built in and you'll need to write a custom script.
