### ISSUE TITLE
CGI path for javascript should be a runtime configuration parameter, not a buildtime option

### ISSUE THREAD

**Issue by guillomovitch** [NagiosEnterprises/nagioscore#833]
The commit #8deeca7cad3df1143ad9c351d107b5c0a6c61213 fixed a vulnerability in javascript by changing runtime discovery of CGI URLs by a value fixed at buildtime (the --cgiurl configure option). However, when the build is decorelated from installation and usage, as it happens with every linux distribution distributing a nagios package, this hardcodes a packager decision in the code, such as '/nagios/cgi-bin' in Fedora, which is unfortunate.

Given there is already a dedicated configuration parameter ($cfg['cgi_base_url']) in config.inc.php, this parameter should probably get propagated to the javascript code, instead of being duplicated and harcoded.

**Comment by sawolf** [comment]
I'm a bit ignorant about how packaging works still, but I'm a bit confused here - if the issue is that the URL is hard-coded for users, I would be surprised if anyone could modify config.inc.php and couldn't also modify the angular sources. I agree that it's probably more annoying to do that, though.

The other side of this is that there's been some link-rot since that change was made, and I can't find the original PoC anymore. In principle, I think you could use PHP code to generate the JS files, which feels messy but shouldn't reopen the vulnerability.
