### ISSUE TITLE
Where are the man pages?

### ISSUE THREAD

**Issue by 0byt3** [NagiosEnterprises/nagioscore#846]
I know this isn't a bug, rather a lack of knowledge on my part, but I hope someone is willing to inform me.
After building and installing nagios-core from source, there is no man page (or at least " man nagios " doesn't work).

I looked at the --help output of the ./configure script and see there is an option to specify "mandir". I'm assuming then that the man pages do exist in the source, I just needed to specify where the directory is for the man pages. Or maybe I need to run a command to rebuild the man pages database and they are there..?

I tried the following to configure, compile and install again:
`./configure --bindir=/usr/bin --sbindir=/usr/sbin --with-httpd-conf=/etc/apache2/sites-available --mandir=/usr/share/man --docdir=/usr/share/doc
make all
make fullinstall`

I am using Debian 11 if Linux distribution matters.

**Comment by ericloyd** [comment]
Nagios is a platform; a system; a collection of many different things.  A man page would not be useful to help you learn it.  You really should read the documentation at https://www.nagios.org/documentation instead.

**Comment by 0byt3** [comment]
> Nagios is a platform; a system; a collection of many different things. A man page would not be useful to help you learn it. You really should read the documentation at https://www.nagios.org/documentation instead.

Do you mean to imply that nagios does not have a man page?
I should have specified that I am installing nagios-core, which, I believe, is 1 component of the suite.

**Comment by ericloyd** [comment]
Yes, I mean exactly that.  It's open source - you can browse this repository and try to find a man page, but I don't believe you will find a man page. 

And since you put this in the Nagios Core Github page, I assumed you were talking about the open source nagios-core.  I am not referring to Nagios XI, which is what I think you mean by "the suite."

Nagios Core consists of the main program, the configuration files that make it work, the plugins that perform the work, and the various pieces that tie all that together.  It is substantially more complex than a simple man page would allow.  This is why I pointed you at the online documentation on Nagios's web page.  You have to know how to configure Core by managing a number of configuration files, each with their own specifications and keywords.  

The /usr/local/nagios/bin/nagios executable does have a help option if you're just looking for how to execute that program, but if you are looking for assistance in "getting started" with Nagios once you've installed it, I really suggest you look at the web page I gave you earlier.
