### ISSUE TITLE
Old Nagios process not killed in core init script

### ISSUE THREAD

**Issue by rcknag** [NagiosEnterprises/nagioscore#89]
The old nagios process is not always killed properly all the time when applying configuration leaving old ones to run in the background.

**Comment by scottwilkerson** [comment]
Additional info
https://support.nagios.com/forum/viewtopic.php?t=35570

**Comment by jfrickson** [comment]
Fixed by commit https://github.com/NagiosEnterprises/nagioscore/commit/f7c6118c794c18b84ce73faa7b2767f847616582
in branch https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1

The init script will now wait up to 90 seconds for the nagios process
to go away by itself. If it doesn't the script will KILL it.
