### ISSUE TITLE
Nagios Docker Issue

### ISSUE THREAD

**Issue by kotso** [NagiosEnterprises/nagioscore#905]
Hello,

We run multiple instances of Nagios (different locations) and all of them are running in docker. 

All been working perfect before we deployed our first Almalinux 9 server (previous servers are AlmaLinux 8 and some been migrated from CentOS 7)

We face very strange error.

On Almalinux 9 (host machine that runs docker) Nagios docker container can not create command file (/var/spool/nagios/nagios.cmd) error in Nagios log says our of memory but it's not correct identification of problem.

Same server with same nagios configuration and same docker-compose file works with no issue on AlmaLinux 8 and CentOS 7.

I thought it could be issue of our private image we are using but it's same on some other images I found on docker hub.

Additionally I tried to run container as privileged but it did not change thing. 

Here is case:

*NOT Working* 

AlmaLinux 9 VM, Docker 23.0.3, selinux disabled.

*Working*

Same VM with Almalinux 8, Docker 23.0.3, selinux disabled.

tried all options I could think of to fix issue for 3 days, no any progress.

to reproduce error, just run public docker image 

`docker run --name nagios-test -p 0.0.0.0:8080:80 manios/nagios:latest`

error will be:

```
wproc: Registry request: name=Core Worker 44;pid=44
2023-04-12T17:27:04.858473+00:00 b4ac23ef9741 : wproc: Registry request: name=Core Worker 44;pid=44
wproc: Registry request: name=Core Worker 45;pid=45
2023-04-12T17:27:05.812151+00:00 b4ac23ef9741 : wproc: Registry request: name=Core Worker 45;pid=45
2023-04-12T17:27:06.763500+00:00 b4ac23ef9741 : wproc: Registry request: name=Core Worker 46;pid=46
wproc: Registry request: name=Core Worker 46;pid=46
wproc: Registry request: name=Core Worker 47;pid=47
2023-04-12T17:27:07.714252+00:00 b4ac23ef9741 : wproc: Registry request: name=Core Worker 47;pid=47
wproc: Registry request: name=Core Worker 48;pid=48
2023-04-12T17:27:08.670751+00:00 b4ac23ef9741 : wproc: Registry request: name=Core Worker 48;pid=48
Failed to fork() command file worker: Out of memory
```

Our private image is based on Almalinux 9, tried to change to 8 without any luck.

Any idea how to troubleshoot further will be much appreciated. 

Also strange is fact that without command file, nagios itself runs fine, only I'm looking options to manage it properly from web interface.

**Comment by ericloyd** [comment]
This isn't really the best place to ask questions about the software.  You should look at the Nagios Forums at https://support.nagios.com/forum and then the Open Source forum (https://support.nagios.com/forum/viewforum.php?f=7) for help on Nagios Core.

Meanwhile, you never mention what Docker image or what version of Nagios you're running, which would be very helpful for general troubleshooting.

**Comment by kotso** [comment]
tried multiple, all behave same, all debuting was mostly done around 4.4.9 and 4.4.10.

I even tracked down nagios source file from where error is initiated: https://github.com/NagiosEnterprises/nagioscore/blob/4e80d5534ef53bcd86bab4a03886cb04f8758e63/base/commands.c#L264

It has not changed for  4 years, so don't think it's some minor version issue.

**Comment by ericloyd** [comment]
Be aware that there is no "official" Docker release for Nagios.  You may want to contact the person who created the Docker image you're using.  

"Same server with same nagios configuration and same docker-compose file works with no issue on AlmaLinux 8 and CentOS 7."

This sounds like it's an OS issue, or a Docker image creation issue, not a Nagios issue.

**Comment by kotso** [comment]
@ericloyd yes I know, just I was desperate to make it working and to make sure it's not my image issue - I tried multiple different public images I found, when all of them behaved same way as my image - got that it's not my issue but more general.

agree about potential os issue. will open same issue to docker, maybe they will be able to help.

**Comment by kotso** [comment]
@ericloyd tried to register on forum ))) still waiting for confirmation/activation email.

about nagios running on server without docker - yes, it works fine.

**Comment by ericloyd** [comment]
I wish I could approve your membership request over there, but I can't!  :-)

So sounds like a Docker build issue to me.

**Comment by sawolf** [comment]
Hi @kotso, thanks for reaching out. 

The first thing I'll say is that I don't know how that docker system is set up and I don't maintain it. Going by the paths, it looks like it might be derived from the debian packages for Nagios Core, but I'm not completely certain about that. What is almost definitely the case is that the configuration comes from https://github.com/manios/docker-nagios - if you want someone who's familiar with that deployment, you should try to contact the maintainer of that repository.

As for your immediate problem, I don't have a ton of time to go through this, but here are some ideas:
 > can not create command file (/var/spool/nagios/nagios.cmd) 
Usually when I see errors like this, it's because the original directories don't exist. Does `/var/spool/nagios` exist? Is it accessible by the nagios group and user?

> error in Nagios log says our of memory but it's not correct identification of problem.
That might still be an issue - if you know for sure that it's not, feel free to ignore me, but in my experience, CentOS 9 (and probably Alma by extension) takes a lot more memory than previous distributions.

Best of luck on your problem! I'm going to close this issue, but if you're able to identify an issue with this repository's code, feel free to create another issue for that.
