### ISSUE TITLE
file to init socket /usr/local/nagios/var/rw/query.sh

### ISSUE THREAD

**Issue by Zey-7** [NagiosEnterprises/nagioscore#931]
Salut! 
La plateforme s'affiche avec un croix rouge Nagios core not running, comment puis je resoudre ce probleme sur nagios core 4.4.14 svp?

**Comment by sawolf** [comment]
Hello @Zey-7, thanks for reaching out! `/usr/local/nagios/var/rw/query.sh` isn't part of the default configuration, but I would start by checking the permissions on the parent directories. Here's what I have on my (working) system:

```
[root@localhost nagioscore]# ll /usr/local/nagios/var/rw/ -d
drwxrwsr-x. 2 nagios nagios 41 Nov  8 16:50 /usr/local/nagios/var/rw/
[root@localhost nagioscore]# ll /usr/local/nagios/var/ -d
drwxrwxr-x. 5 nagios nagios 144 Nov  8 17:01 /usr/local/nagios/var/
[root@localhost nagioscore]# ll /usr/local/nagios/ -d
drwxr-xr-x. 8 root root 79 Jan 16  2023 /usr/local/nagios/
```
You may also want to check that the file itself is owned by `nagios:nagios` (instead of, e.g. root):
```
[root@localhost nagioscore]# ll /usr/local/nagios/var/rw
total 0
prw-rw---- 1 nagios nagios 0 Nov  8 16:52 nagios.cmd
srw-rw---- 1 nagios nagios 0 Nov  8 16:50 nagios.qh
[root@localhost nagioscore]# 
```

Hopefully that helps - if you have any further concerns, I would open a thread on our [Support Forums](https://support.nagios.com/forum/) - there are more people over there who are able to help you.
